gnodeb:
  controlif: # N1/2
    ip: "172.16.5.63"
    port: 9487
  dataif: # N3
    ip: "172.16.5.63"
    port: 2152
  plmnlist:
    mcc: "208"
    mnc: "93"
    tac: "000001"
    gnbid: "000008"
  slicesupportlist:
    sst: "01"
    sd: "010203" # optional, can be removed if not used

ue:
  msin: "0000000001"
  key: "8baf473f2f8fd09487cccbd7097c6862"
  opc: "8e27b6af0e692e750f32667a3b14605d"
  op: "8e27b6af0e692e750f32667a3b14605d"
  amf: "8000"
  sqn: "000000000005"
  dnn: "internet"
  routingindicator: "0000"
  hplmn:
    mcc: "208"
    mnc: "93"
  snssai:
    sst: 01
    sd: "010203" # optional, can be removed if not used
  integrity:
    nia0: false
    nia1: false
    nia2: true
    nia3: false
  ciphering:
    nea0: true
    nea1: false
    nea2: true
    nea3: false
amfif:
  ip: "172.16.5.60"
  port: 38412
logs:
    level: 4
